### ISSUE TITLE
error with taskrunner-java

### ISSUE THREAD

**Issue by seblemaguer** [emacs-taskrunner/emacs-taskrunner#1]
Hello,

by executing this command: 

```elisp
(taskrunner-get-gradle-tasks ".")
```

I face this error:

```
Debugger entered--Lisp error: (invalid-function taskrunner--make-task-buff-name)
  taskrunner--make-task-buff-name("gradle")
  taskrunner-get-gradle-tasks(".")
  eval((taskrunner-get-gradle-tasks ".") nil)
  eval-expression((taskrunner-get-gradle-tasks ".") nil nil 127)
  funcall-interactively(eval-expression (taskrunner-get-gradle-tasks ".") nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

For the installation, I am simply using the melpa package:
```elisp
(use-package taskrunner :ensure t)
```

**Comment by sehnsucht13** [comment]
Thanks for the report. I will take a look at it as soon as possible!

**Comment by seblemaguer** [comment]
I tried, helm-taskrunner and ivy-runner (but using quelpa) which triggered the problem. Then I reduced it to the "example" written above. But I am really looking forward to use the package :)

**Comment by sehnsucht13** [comment]
Thanks a lot for the info and thanks for taking time to narrow down the problem! I will take a closer look today and willl notify you with any changes!

**Comment by sehnsucht13** [comment]
Hi, sorry for the wait. I have implemented a fix. Please update the package, try everything out again and let me know if it works. The next MELPA build should start soon so the files will be updated then. I have tested it out and it should do the trick.

**Comment by seblemaguer** [comment]
Thanks, I will try it a little bit later as I am currently at a conference.

**Comment by seblemaguer** [comment]
Yup, it is solved and tested with ivy-taskrunner. Thanks a lot.
